### PR TITLE
Use cmake FULL variables for pkgconfig libdir and includedir

### PR DESCRIPTION
**Pull request by j-rivero**
Back to use the FULL cmake variables. It was removed in 27de5f2f607c6d5b6aae66175503d7e56729a2b7

### CODE REVIEW

**Comment by scpeters** [comment]
It looks like they were using `CMAKE_INSTALL_LIBDIR` and `CMAKE_INSTALL_INCLUDEDIR` before, not the `FULL` versions. What is the difference?

**Comment by j-rivero** [comment]
> It looks like they were using CMAKE_INSTALL_LIBDIR and CMAKE_INSTALL_INCLUDEDIR before, not the FULL versions. What is the difference?

When using [GNUInstallDirs](https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html), the FULL variables represent absolute path. From that file:

```
# Each CMAKE_INSTALL_FULL_<dir> value contains an absolute path constructed
# from the corresponding destination by prepending (if necessary) the value
# of CMAKE_INSTALL_PREFIX.
```

**Comment by scpeters** [comment]
@jpgr87 what do you think?

**Comment by jpgr87** [comment]
It's basically equivalent to `${prefix}/@CMAKE_INSTALL_*`, I think it's fine to do it this way.

**Comment by scpeters** [comment]
+1

thanks @j-rivero and @jpgr87

**Pull request merged**
