### PR TITLE
Added Doxyfile

### PR DESCRIPTION
**Pull request by ahcorde**
We need to include the documentation of this package upstream to reach Quality Level 1

Just run to generate the documentation

```
doxygen Doxifile
```

Signed-off-by: ahcorde <ahcorde@gmail.com>

### CODE REVIEW

**Comment by ahcorde** [comment]
friendly ping @scpeters

**Comment by scpeters** [comment]
sorry for the delay; I wanted to add CI for generating the doxygen, so I added a GitHub action for this; what do you think?

**Review by scpeters — APPROVED** [review]

**Comment by ahcorde** [comment]
graphiz is not installed.

```
sh: 1: dot: not found
```

**Comment by scpeters** [comment]
> graphiz is not installed.
> 
> ```
> sh: 1: dot: not found
> ```


f6e4d88

**Pull request merged**
