### PR TITLE
Make CMake configuration files relocatable 

### PR DESCRIPTION
**Pull request by traversaro**
See discussion in https://github.com/ros/console_bridge/issues/44 .

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
:+1: 

Tested this PR with ros2 and it solves the problem of not being able to find console_bridge.

(The original problem being the console_bridge-config.cmake file keeps an absolute path of the building machine for include and library folders. So it cannot be deployed to another location or another machine with a different folder structure)

**Comment by nuclearsandwich** [comment]
@mikaelarguedas will this PR be necessary for console_bridge in beta2?

**Comment by mikaelarguedas** [comment]
@nuclearsandwich Sorry I forgot to reply to that after we discussed it offline. Yes this needs to be in if we want users to be able to build packages on top of our binaries / archives. The only scenario it would work without this change is for linux users using debian packages.

@j-rivero @scpeters any chance to get this reviewed and merged in the near future?

**Comment by nuclearsandwich** [comment]
> any chance to get this reviewed and merged in the near future?

Review would certainly be welcome and I'd love to get back to tracking master for future releases, but this would not block beta2 if it waited since the packaged build is based my branch here: https://github.com/ros/console_bridge/pull/46 which incorporates this branch as well as some others.

**Comment by mikaelarguedas** [comment]
> since the packaged build is based my branch here: #4

It's only the deb packaging jobs right? not the packaging jobs for the other platforms? I agree we could track that in the meantime

**Comment by scpeters** [comment]
sorry for the delay in reviewing, this looks great!

**Pull request merged**
