### PR TITLE
Remove deprecated macros

### LINKED ISSUE #18: change naming of defines to include namespace
The currently defined macros to log messages (e.g. https://github.com/ros/console_bridge/blob/7aebc3367b4945d9963457549026ea137b047b7b/include/console_bridge/console.h#L68) are much to generic and collide with existing code. The should be prefixed with the package name to make them unique.

Even if this is a significant API change this should be fixed. Likely bumping more then just the patch version number.

### PR DESCRIPTION
**Pull request by scpeters**
Closes #18.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The order of the commits seems wrong to me.

**Comment by scpeters** [comment]
I just changed the order of commits

**Comment by mikaelarguedas** [comment]
thanks @scpeters for the super quick action on this !

**Comment by scpeters** [comment]
I'll merge after an approval

**Comment by mikaelarguedas** [comment]
The change looks good to me :+1: . Though I don't have authority here

**Pull request merged**
