### PR TITLE
Implement the use of the generate_export_header cmake macro

### PR DESCRIPTION
**Pull request by j-rivero**
After discussion in #42 following @traversaro suggestion in #40 

I've tested it Ubuntu Xenial with GCC 5.4.0 and Windows7 with MSVC 2013.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
See https://github.com/ros2/rmw_fastrtps/pull/87#issuecomment-289530141

**Comment by scpeters** [comment]
I've been peeking at the cmake source code, and I think this requires cmake 2.8.6 since it exists here:

* https://github.com/Kitware/CMake/blob/v2.8.6/Modules/GenerateExportHeader.cmake

but not in 2.8.5:

* https://github.com/Kitware/CMake/blob/v2.8.5/Modules/GenerateExportHeader.cmake

Should we upgrade the cmake version requirement in CMakeLists.txt?

**Comment by j-rivero** [comment]
> Should we upgrade the cmake version requirement in CMakeLists.txt?

done in c322c60

**Comment by esteve** [comment]
Is there anything pending? The changes look good to me and would help https://github.com/ros2/rmw_fastrtps/pull/87 a lot.

**Comment by scpeters** [comment]
Thanks for the ping @esteve; it looks good to me too. Is it enough for ros2 to have this in the master branch, or do we need another release?

**Comment by mikaelarguedas** [comment]
master branch is fine :+1: , thanks !

**Comment by dirk-thomas** [comment]
For now we can use the `master` branch. But for future binary releases (targeted for beta 2) this change needs to be available as a Debian package (in Xenial).

**Comment by scpeters** [comment]
Well, we can ask @j-rivero if he thinks a 0.3.3 could make it into xenial. Otherwise it could be hosted on our package server or a PPA.

**Comment by j-rivero** [comment]
> Well, we can ask @j-rivero if he thinks a 0.3.3 could make it into xenial. Otherwise it could be hosted on our package server or a PPA.

Given the situation, I think that we hardly can argue that this fix falls under the [Stable Release Update](https://wiki.ubuntu.com/StableReleaseUpdates#When) category. If the new version only includes this patch or do not touch the ABI it is fine to host it in any of our repositories. If the current `master` branch alters the ABI, we can cherry pick this change as a patch on top of the Xenial release.

**Comment by esteve** [comment]
@scpeters thanks for merging the PR, this should pave the way for https://github.com/ros2/rmw_fastrtps/pull/87 to be merged as well.

**Comment by scpeters** [comment]
@j-rivero if I released 0.3.3 today, could it get into Ubuntu zesty?

**Comment by j-rivero** [comment]
> @j-rivero if I released 0.3.3 today, could it get into Ubuntu zesty?

A bit late since it is [Final Freeze](http://www.compatdb.org/forums/topic/116432-zesty-zapus-1704-final-freeze/) and the policies for Stable Release Updates (SRUs) applied also to this final step.

**Pull request merged**
