### PR TITLE
Add duplicate macros with namespace prefix

### PR DESCRIPTION
**Pull request by scpeters**
Add duplicate macros to console.h with `CONSOLE_BRIDGE_` prepended.

First step in fixing #18. These new macros can be released in a patch release, then we will remove the old macros when bumping the major or minor.

@dirk-thomas

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The "deprecated" macros should actually result in a deprecation warning in order for users to notice that they should update their code using console bridge.

**Comment by dirk-thomas** [comment]
The question will be how should this be rolled out:

1. A patch release now with the namespaced API added, a major release with the old API being released in Xenial.
2. Add the new API in Xenial together with deprecating the old API, remove the old API in Ubuntu Z / ROS L.

**Comment by scpeters** [comment]
deprecation warnings in b6d96f9

**Comment by scpeters** [comment]
I vote for 2

**Comment by scpeters** [comment]
I also bumped the minor (509ca97) since adding the deprecation warnings

**Comment by scpeters** [comment]
@j-rivero how possible is it to patch the current version of `libconsole-bridge` in trusty with 87c68933dde0de9fe8e66f9a4c193ce3c42f4f6c?

**Comment by j-rivero** [comment]
> @j-rivero how possible is it to patch the current version of libconsole-bridge in trusty with 87c6893?

We would need to demostrate that if fixes a critical bug, which I believe that would be quite a hard work this time.

**Comment by scpeters** [comment]
I'd like to make a new release. I'll merge this within the next few hours if I don't hear any other comments.

**Pull request merged**
